const images = {
    noImage: require('./no-img.jpeg'),
    bgHero1Pc: require('./bg-hero-1-1792-x2.jpeg'),
    bgHero1Tablet: require('./bg-hero-1-900-x2.png'),
    bgHero2Pc: require('./bg-hero-2-1792-x2.jpeg'),
    bgHero2Tablet: require('./bg-hero-2-900-x2.png'),
    bgHero3Pc: require('./bg-hero-3-1792-x2.jpeg'),
    bgHero3Tablet: require('./bg-hero-3-900-x2.png'),
    bgHero4Pc: require('./bg-hero-4-1792-x2.jpeg'),
    bgHero4Tablet: require('./bg-hero-4-900-x2.png'),
    bgHero5Pc: require('./bg-hero-5-1792-x2.jpeg'),
    bgHero5Tablet: require('./bg-hero-5-900-x2.png'),
    facebookLogo: require('./facebook-logo.png'),
    googleLogo: require('./google-logo.png'),
    netflixLogo: require('./netflix-logo.png'),
    pandgLogo: require('./pandg-logo.png'),
    paypalLogo: require('./paypal-logo.png'),
    serviceBg1: require('./service-bg-1.jpeg'),
    serviceBg2: require('./service-bg-2.jpeg'),
    serviceBg3: require('./service-bg-3.jpeg'),
    serviceBg4: require('./service-bg-4.jpeg'),
    serviceBg5: require('./service-bg-5.jpeg'),
    serviceBg6: require('./service-bg-6.jpeg'),
    serviceBg7: require('./service-bg-7.jpeg'),
    serviceBg8: require('./service-bg-8.jpeg'),
    serviceBg9: require('./service-bg-9.jpeg'),
    serviceBg10: require('./service-bg-10.jpeg'),
    sellingVidCover: require('./selling-vid-cover.png'),
};

export default images;
